"""
medical_knowledge.py — Python medical knowledge base (RAG source)
GenAI Pattern: RAG (Retrieval-Augmented Generation) data source
"""

SYMPTOM_GROUPS = {
    "fever": ["fever","high temperature","hot body","chills","shivering","burning up","feverish","pyrexia"],
    "headache": ["headache","head pain","migraine","throbbing head","head hurts","pressure in head"],
    "fatigue": ["fatigue","tiredness","weakness","weak","exhausted","lethargy","no energy","feel weak"],
    "cough": ["cough","coughing","dry cough","wet cough","persistent cough"],
    "breathless": ["breathless","shortness of breath","difficulty breathing","can't breathe","dyspnea","hard to breathe"],
    "chest_pain": ["chest pain","chest tightness","chest pressure","tight chest","chest ache"],
    "nausea": ["nausea","nauseous","feel sick","want to vomit","queasy","upset stomach"],
    "vomiting": ["vomiting","vomit","throwing up","threw up","puking"],
    "diarrhea": ["diarrhea","loose stool","watery stool","loose motion","frequent stools"],
    "abdominal": ["abdominal pain","stomach pain","belly pain","tummy ache","cramps","stomach cramp"],
    "sore_throat": ["sore throat","throat pain","scratchy throat","painful throat","difficulty swallowing"],
    "rash": ["rash","skin rash","redness","spots","hives","itching","itchy skin"],
    "joint_pain": ["joint pain","joint ache","bone pain","muscle ache","body ache","myalgia"],
    "swelling": ["swelling","edema","bloating","puffiness","swollen"],
    "dizziness": ["dizziness","dizzy","vertigo","lightheaded","fainting","spinning"],
    "confusion": ["confusion","confused","disoriented","memory loss","brain fog"],
    "anxiety": ["anxiety","anxious","panic","stress","worry","nervous","restless"],
    "vision": ["blurry vision","vision loss","double vision","eye pain","yellow eyes"],
    "jaundice": ["jaundice","yellow skin","skin yellow","yellowing"],
    "urinary": ["burning urination","frequent urination","painful urination","blood in urine","dark urine"],
    "bleeding": ["bleeding","blood","hemorrhage","nosebleed","bleeding gums","blood in stool"],
    "numbness": ["numbness","tingling","pins and needles","loss of sensation"],
    "weight_loss": ["weight loss","losing weight","sudden weight loss","unexplained weight loss"],
    "appetite": ["loss of appetite","no appetite","not hungry","not eating"],
    "palpitations": ["palpitations","heart racing","heart pounding","rapid heartbeat","irregular heartbeat"],
    "runny_nose": ["runny nose","nasal congestion","stuffy nose","blocked nose","sneezing"],
    "back_pain": ["back pain","lower back pain","backache","spine pain"],
    "sleep": ["insomnia","can't sleep","sleeplessness","sleep problems","disturbed sleep"],
    "thirst": ["excessive thirst","very thirsty","drinking a lot of water","polydipsia"],
    "frequent_urination": ["frequent urination","urinating a lot","polyuria","peeing a lot"],
    "wheezing": ["wheezing","whistling breath","noisy breathing"],
    "night_sweats": ["night sweats","sweating at night","waking up sweating"],
    "sweating": ["sweating","excessive sweating","profuse sweat","perspiring"],
    "neck_stiffness": ["neck stiffness","stiff neck","neck pain","cannot move neck"],
    "seizures": ["seizure","convulsion","fits","epilepsy","shaking uncontrollably","blackout"],
    "tremors": ["tremors","shaking","hand trembling","body trembling","shaky"],
    "heartburn": ["heartburn","acid reflux","burning in chest","sour taste","indigestion","gerd"],
    "phlegm": ["phlegm","mucus","sputum","coughing up phlegm","productive cough"],
    "depression": ["depression","sad","hopeless","depressed","low mood","feeling down","emptiness"],
    "heat_intolerance": ["sensitive to heat","heat intolerance","feel very hot","overheating"],
    "weight_gain": ["weight gain","gaining weight","sudden weight gain"],
    "muscle_weakness": ["muscle weakness","can't lift","arms weak","legs weak","limb weakness"],
    "sensitivity_light": ["sensitivity to light","photophobia","light hurts eyes"],
    "sensitivity_sound": ["sensitivity to sound","phonophobia","noise sensitivity"],
    "muscle_spasms": ["muscle spasms","muscle cramps","muscle twitching","leg cramps"],
    "dry_skin": ["dry skin","skin dryness","flaky skin","scaly skin"],
    "peeling_skin": ["peeling skin","skin peeling","blistering","blisters"],
    "increased_appetite": ["increased appetite","always hungry","polyphagia","excessive hunger"],
}

DISEASES = [
    {
        "id": "common_cold", "name": "Common Cold / Viral URTI", "icd": "J06.9",
        "symptoms": ["fever","runny_nose","sore_throat","cough","fatigue","headache"],
        "required": ["runny_nose","sore_throat"],
        "weight": {"fever":1,"runny_nose":3,"sore_throat":3,"cough":2,"fatigue":1,"headache":1},
        "base_risk": 10, "urgency": "low",
        "specialist": "General Practitioner",
        "lifestyle": ["Stay warm and rest","Drink warm fluids (herbal tea, broth)","Saline nasal rinse","Vitamin C supplementation","Avoid smoking"],
    },
    {
        "id": "influenza", "name": "Influenza (Flu)", "icd": "J11",
        "symptoms": ["fever","fatigue","headache","joint_pain","cough","runny_nose","sore_throat"],
        "required": ["fever","fatigue"],
        "weight": {"fever":3,"fatigue":3,"headache":2,"joint_pain":2,"cough":2,"runny_nose":1},
        "base_risk": 25, "urgency": "moderate",
        "specialist": "General Practitioner / Infectious Disease",
        "lifestyle": ["Complete bed rest","High fluid intake","Antiviral may be prescribed","Isolate from others","Annual flu vaccine advised"],
    },
    {
        "id": "dengue", "name": "Dengue Fever", "icd": "A90",
        "symptoms": ["fever","headache","joint_pain","rash","nausea","vomiting","bleeding","fatigue"],
        "required": ["fever","joint_pain"],
        "weight": {"fever":4,"headache":2,"joint_pain":4,"rash":3,"nausea":1,"bleeding":4,"fatigue":2},
        "base_risk": 65, "urgency": "high",
        "specialist": "Infectious Disease Specialist / Emergency Medicine",
        "lifestyle": ["Strict bed rest","Monitor platelet count daily","Avoid NSAIDs (aspirin, ibuprofen)","Papaya leaf extract (consult doctor)","Mosquito net use"],
    },
    {
        "id": "malaria", "name": "Malaria", "icd": "B54",
        "symptoms": ["fever","headache","fatigue","nausea","vomiting","joint_pain","sweating"],
        "required": ["fever","fatigue"],
        "weight": {"fever":4,"fatigue":3,"headache":2,"nausea":2,"vomiting":2,"joint_pain":2},
        "base_risk": 70, "urgency": "high",
        "specialist": "Infectious Disease Specialist",
        "lifestyle": ["Strict prescribed antimalarial medication","Complete the full course","Mosquito-proof your environment","Avoid outdoor exposure at dusk/dawn","Blood test for confirmation is essential"],
    },
    {
        "id": "typhoid", "name": "Typhoid Fever", "icd": "A01.0",
        "symptoms": ["fever","headache","fatigue","abdominal","diarrhea","nausea","appetite","rash"],
        "required": ["fever","abdominal"],
        "weight": {"fever":4,"headache":2,"fatigue":2,"abdominal":3,"diarrhea":2,"nausea":2,"appetite":2},
        "base_risk": 60, "urgency": "high",
        "specialist": "Infectious Disease Specialist / Gastroenterologist",
        "lifestyle": ["Maintain strict food hygiene","Drink only boiled/filtered water","Complete antibiotic course","Light, easily digestible foods","Vaccination recommended after recovery"],
    },
    {
        "id": "covid19", "name": "COVID-19", "icd": "U07.1",
        "symptoms": ["fever","cough","fatigue","breathless","headache","sore_throat"],
        "required": ["fever","cough"],
        "weight": {"fever":3,"cough":3,"fatigue":2,"breathless":4,"headache":1,"sore_throat":1},
        "base_risk": 55, "urgency": "high",
        "specialist": "Pulmonologist / Emergency Medicine",
        "lifestyle": ["Isolate for at least 5-10 days","Monitor oxygen levels (SpO2 > 95%)","Rest and hydrate","Contact tracing required","Consult doctor for antiviral options"],
    },
    {
        "id": "gastroenteritis", "name": "Acute Gastroenteritis", "icd": "A09",
        "symptoms": ["nausea","vomiting","diarrhea","abdominal","fever","fatigue"],
        "required": ["nausea","diarrhea"],
        "weight": {"nausea":3,"vomiting":2,"diarrhea":3,"abdominal":2,"fever":1,"fatigue":1},
        "base_risk": 30, "urgency": "moderate",
        "specialist": "General Practitioner / Gastroenterologist",
        "lifestyle": ["Oral rehydration solution (ORS) is critical","Bland BRAT diet (banana, rice, applesauce, toast)","Avoid dairy and fatty foods","Hand hygiene strictly","Probiotics may help recovery"],
    },
    {
        "id": "pneumonia", "name": "Pneumonia", "icd": "J18",
        "symptoms": ["fever","cough","breathless","chest_pain","fatigue","nausea"],
        "required": ["fever","cough","breathless"],
        "weight": {"fever":3,"cough":3,"breathless":4,"chest_pain":3,"fatigue":2},
        "base_risk": 75, "urgency": "high",
        "specialist": "Pulmonologist / Emergency Medicine",
        "lifestyle": ["Hospital evaluation strongly recommended","Complete prescribed antibiotic/antiviral course","Steam inhalation may help","Avoid cold air","Pneumococcal vaccination after recovery"],
    },
    {
        "id": "diabetes_t2", "name": "Type 2 Diabetes (Suspected)", "icd": "E11",
        "symptoms": ["thirst","frequent_urination","fatigue","vision","weight_loss","numbness"],
        "required": ["thirst","frequent_urination"],
        "weight": {"thirst":4,"frequent_urination":4,"fatigue":2,"vision":2,"weight_loss":3,"numbness":2},
        "base_risk": 50, "urgency": "moderate",
        "specialist": "Endocrinologist / Diabetologist",
        "lifestyle": ["Monitor blood glucose regularly","Low glycaemic index diet","Regular 30-min walks","Reduce sugar and refined carbs","Doctor to evaluate HbA1c"],
    },
    {
        "id": "hypertension", "name": "Hypertension (High Blood Pressure)", "icd": "I10",
        "symptoms": ["headache","dizziness","palpitations","vision","chest_pain","fatigue"],
        "required": ["headache","dizziness"],
        "weight": {"headache":3,"dizziness":3,"palpitations":2,"vision":2,"chest_pain":3,"fatigue":1},
        "base_risk": 55, "urgency": "moderate",
        "specialist": "Cardiologist / General Physician",
        "lifestyle": ["DASH diet (low sodium, high potassium)","Reduce salt intake","Regular aerobic exercise","Limit alcohol; quit smoking","Stress reduction (yoga/meditation)"],
    },
    {
        "id": "heart_attack", "name": "Myocardial Infarction (Heart Attack)", "icd": "I21",
        "symptoms": ["chest_pain","breathless","palpitations","fatigue","nausea","dizziness","numbness"],
        "required": ["chest_pain"],
        "weight": {"chest_pain":5,"breathless":4,"palpitations":3,"fatigue":2,"nausea":2,"dizziness":2,"numbness":3},
        "base_risk": 90, "urgency": "emergency",
        "specialist": "Emergency Medicine / Cardiologist",
        "lifestyle": ["Call 108/911 IMMEDIATELY","Chew aspirin 325mg if not allergic","Do not drive yourself","Keep patient calm and still","CPR if consciousness is lost"],
    },
    {
        "id": "appendicitis", "name": "Appendicitis", "icd": "K37",
        "symptoms": ["abdominal","fever","nausea","vomiting","appetite"],
        "required": ["abdominal","fever"],
        "weight": {"abdominal":5,"fever":3,"nausea":2,"vomiting":2,"appetite":2},
        "base_risk": 80, "urgency": "emergency",
        "specialist": "Emergency Medicine / General Surgeon",
        "lifestyle": ["Emergency surgery may be required","Nothing by mouth (NPO)","Rush to the nearest hospital","Do NOT apply heat to abdomen","Note exact location and time of pain onset"],
    },
    {
        "id": "migraine", "name": "Migraine", "icd": "G43",
        "symptoms": ["headache","nausea","vision","dizziness","fatigue","vomiting"],
        "required": ["headache"],
        "weight": {"headache":5,"nausea":2,"vision":3,"dizziness":2,"fatigue":1,"vomiting":2},
        "base_risk": 25, "urgency": "low",
        "specialist": "Neurologist",
        "lifestyle": ["Rest in a dark, quiet room","Cold or warm compress on forehead","Triptans prescribed by neurologist","Identify triggers (stress, foods, lights)","Maintain regular sleep schedule"],
    },
    {
        "id": "uti", "name": "Urinary Tract Infection (UTI)", "icd": "N39.0",
        "symptoms": ["urinary","frequent_urination","fever","abdominal","fatigue"],
        "required": ["urinary"],
        "weight": {"urinary":5,"frequent_urination":3,"fever":2,"abdominal":2,"fatigue":1},
        "base_risk": 35, "urgency": "moderate",
        "specialist": "Urologist / General Practitioner",
        "lifestyle": ["Increase fluid intake (cranberry juice helps)","Complete antibiotic course","Urinate frequently — don't hold","Maintain personal hygiene","Avoid caffeinated drinks"],
    },
    {
        "id": "anaemia", "name": "Anaemia", "icd": "D64",
        "symptoms": ["fatigue","dizziness","breathless","palpitations","headache","vision","appetite"],
        "required": ["fatigue","dizziness"],
        "weight": {"fatigue":4,"dizziness":3,"breathless":2,"palpitations":2,"headache":1},
        "base_risk": 35, "urgency": "moderate",
        "specialist": "Haematologist / General Physician",
        "lifestyle": ["Iron-rich diet (spinach, lentils, red meat)","Vitamin B12-rich foods or supplements","Iron supplements as prescribed","Avoid tea/coffee with meals","Regular CBC blood tests"],
    },
    {
        "id": "stroke", "name": "Stroke (Cerebrovascular Accident)", "icd": "I64",
        "symptoms": ["confusion","numbness","vision","headache","dizziness","chest_pain"],
        "required": ["confusion","numbness"],
        "weight": {"confusion":5,"numbness":4,"vision":3,"headache":2,"dizziness":3},
        "base_risk": 95, "urgency": "emergency",
        "specialist": "Neurologist / Emergency Medicine",
        "lifestyle": ["Emergency medical care immediately","Note time of symptom onset (critical for treatment window)","FAST test: Face drooping, Arm weakness, Speech difficulty, Time to call","Do not give food or water","Thrombolytic therapy window is 4.5 hours"],
    },
    {
        "id": "asthma", "name": "Asthma", "icd": "J45",
        "symptoms": ["breathless","wheezing","cough","chest_pain","anxiety"],
        "required": ["breathless","wheezing"],
        "weight": {"breathless":5,"wheezing":5,"cough":3,"chest_pain":2,"anxiety":1},
        "base_risk": 50, "urgency": "high",
        "specialist": "Pulmonologist / Allergist",
        "lifestyle": ["Use prescribed inhaler immediately","Avoid known triggers (dust, pollen, smoke)","Sit upright during an attack","Pursed-lip breathing exercises","Maintain a clean, dust-free environment"],
    },
    {
        "id": "tuberculosis", "name": "Tuberculosis (TB)", "icd": "A15",
        "symptoms": ["cough","night_sweats","weight_loss","fatigue","fever","phlegm","chest_pain"],
        "required": ["cough","night_sweats"],
        "weight": {"cough":4,"night_sweats":4,"weight_loss":3,"fatigue":2,"fever":2,"phlegm":3,"chest_pain":2},
        "base_risk": 70, "urgency": "high",
        "specialist": "Pulmonologist / Infectious Disease",
        "lifestyle": ["Complete the full DOTS antibiotic course (6+ months)","Isolate from others especially elderly/children","High-protein, nutritious diet","Regular chest X-ray monitoring","Wear a mask in public spaces"],
    },
    {
        "id": "meningitis", "name": "Meningitis", "icd": "G03",
        "symptoms": ["neck_stiffness","fever","headache","sensitivity_light","sensitivity_sound","confusion","vomiting"],
        "required": ["neck_stiffness","fever"],
        "weight": {"neck_stiffness":5,"fever":4,"headache":3,"sensitivity_light":3,"confusion":3,"vomiting":2},
        "base_risk": 90, "urgency": "emergency",
        "specialist": "Neurologist / Emergency Medicine",
        "lifestyle": ["Emergency hospitalisation — do NOT delay","IV antibiotics started immediately","Isolation and contact tracing","Monitor for sepsis signs","Lumbar puncture may be needed for diagnosis"],
    },
    {
        "id": "depression", "name": "Major Depressive Disorder", "icd": "F32",
        "symptoms": ["depression","fatigue","sleep","appetite","anxiety","confusion","weight_loss"],
        "required": ["depression"],
        "weight": {"depression":5,"fatigue":3,"sleep":2,"appetite":2,"anxiety":2,"confusion":2},
        "base_risk": 25, "urgency": "moderate",
        "specialist": "Psychiatrist / Clinical Psychologist",
        "lifestyle": ["Cognitive Behavioural Therapy (CBT) is highly effective","Regular physical activity — even 30-min walks help","Maintain a routine and social connections","Antidepressants only as prescribed","Emergency: call a helpline if thoughts of self-harm"],
    },
]

IMMEDIATE_ACTIONS = {
    "emergency": {
        "label": "🚨 CALL EMERGENCY NOW",
        "color": "#ff2d55",
        "bg_color": "rgba(255,45,85,0.15)",
        "actions": [
            "Call 108 (India) / 911 (USA) / 999 (UK) immediately",
            "Do NOT drive yourself — call an ambulance",
            "Stay calm and keep the patient still",
            "Loosen tight clothing",
            "Note the time symptoms started",
        ],
    },
    "high": {
        "label": "⚠️ VISIT HOSPITAL TODAY",
        "color": "#ff9f0a",
        "bg_color": "rgba(255,159,10,0.15)",
        "actions": [
            "Visit the nearest emergency room or hospital today",
            "Do not delay — condition may worsen quickly",
            "Avoid self-medication",
            "Stay hydrated with water or ORS",
            "Keep someone with you",
        ],
    },
    "moderate": {
        "label": "📋 CONSULT DOCTOR SOON",
        "color": "#ffd60a",
        "bg_color": "rgba(255,214,10,0.15)",
        "actions": [
            "Schedule a doctor's appointment within 24–48 hours",
            "Monitor your temperature and symptoms",
            "Stay hydrated and take proper rest",
            "You may take OTC paracetamol if needed",
            "Keep a log of your symptoms",
        ],
    },
    "low": {
        "label": "✅ SELF-CARE LIKELY SUFFICIENT",
        "color": "#30d158",
        "bg_color": "rgba(48,209,88,0.15)",
        "actions": [
            "Rest and stay hydrated",
            "Consume light, nutritious meals",
            "Take OTC medicines as appropriate",
            "Monitor symptoms — revisit if worsening",
            "Schedule a routine GP visit if symptoms persist > 3 days",
        ],
    },
}

# Cross-examination question templates (GenAI seeds these with LLM)
CROSS_EXAM_QUESTIONS = {
    "fever":          "How long have you had the fever and have you measured your temperature?",
    "headache":       "Where is the headache — forehead, temples, or all over? Is it throbbing or pressure-like?",
    "chest_pain":     "Can you describe the chest pain? Is it sharp, dull pressure, or burning? Does it radiate to your arm or jaw?",
    "breathless":     "When does the breathlessness occur — at rest, during mild activity, or only with exertion?",
    "cough":          "Is your cough dry or producing phlegm? How long have you had it?",
    "nausea":         "Is the nausea constant or comes and goes? Have you actually vomited?",
    "dizziness":      "Does the dizziness feel like the room is spinning (vertigo) or lightheadedness? Does it occur when standing up?",
    "joint_pain":     "Which joints are affected? Is there swelling or redness? Is it worse in the morning?",
    "fatigue":        "How severe is the fatigue — are you able to do daily activities? How long have you felt this way?",
    "rash":           "Where on your body is the rash? Is it itchy, raised, or spreading?",
    "abdominal":      "Where exactly is the stomach pain — upper, lower, left, right, or all over? Is it constant or crampy?",
    "urinary":        "Is there burning when you urinate? Is there any blood in the urine or unusual colour/smell?",
    "back_pain":      "Is the back pain in the upper or lower back? Does it radiate to your legs or around to your abdomen?",
    "palpitations":   "Does your heart racing come on suddenly? Does it happen at rest or with activity?",
    "swelling":       "Which part of the body is swollen? Is it painful to touch? Has it come on suddenly?",
    "vision":         "Is it blurry vision in one or both eyes? Did it come on suddenly or gradually?",
}
